default:
  adapter: postgresql
  encoding: unicode
  database: interactive_portfolio_development
  pool: 5
  username: postgres
  password: <%= ENV['DB_PASS'] %>
  timeout: 5000



development:
  adapter: postgresql
  encoding: unicode
  database: interactive_portfolio_development
  pool: 5
  username: postgres
  password: <%= ENV['DB_PASS'] %>
  timeout: 5000
 
test:
  adapter: postgresql
  encoding: unicode
  database: interactive_portfolio_test
  pool: 5
  username: postgres
  password: <%= ENV['DB_PASS'] %>
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: interactive_portfolio_development
  pool: 5
  username: postgres
  password: <%= ENV['DB_PASS'] %>
  timeout: 5000
